version: '3'

services:
  spring-app:
    image: spring-app-image
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres-image
    ports:
      - "5432:5432"

